### ISSUE TITLE
Inserir arquivo de áudio existente

### ISSUE THREAD

**Issue by flavialin** [INNoWay/EditorMm#3]

**Comment by newtonjose** [comment]
Acho que essa resposta dessa questão: http://stackoverflow.com/questions/14412027/can-an-svg-contain-audio-using-javascript possa contribuir com suas pesquisa da possibilidade de inserir áudio.

**Comment by giocoutinho** [comment]
Tentar utilizar uma biblioteca que trabalha com audio em SVG.
Links para serem analisados:
http://www.coreymwamba.co.uk/testbed/svgplayer.html
http://snapsvg.io/

**Comment by giocoutinho** [comment]
Com a tag foreignObject e a tag switch consegui inserir a tag de audio do HTML5 dentro do SVG ou até a tag de vídeo, fiz o teste inserindo o iframe de incorporação de vídeos do youtube e o vídeo foi reproduzido. Agora o próximo passo é aprimorar o uso dessas tags no editor.

**Comment by giocoutinho** [comment]
Não completo, o arquivo ainda não é recuperado do banco e não pode ser deletado ainda também.
